/*
 * 回放数据 —— 全部逐字摘自本仓库中真实运行产生的报告，未做任何润色或虚构。
 *
 *   验收回放（runs）:
 *     reports/npc_real_acceptance/report.json          2026-08-08  qwen3:latest  11/11 PASS
 *     reports/npc_real_acceptance_boundaries/report.json 2026-08-13  qwen3:14b     10/11
 *   提问与游戏状态:
 *     scripts/run_real_npc_acceptance.py（_request 构造的请求字段）
 *   角色声线（voices）:
 *     reports/npc_dialogue_ab/report.json              真实 qwen3 输出，baseline / candidate 两版
 *
 * 说明：A/B 报告只记录了 scenario_id，未记录提问原文，因此声线区块只展示真实答案与场景标识。
 */

window.DEMO_DATA = {
  meta: {
    title: "《归潮之岛》AI NPC 后端",
    subtitle: "验收回放 · 全部台词与指标来自真实运行记录",
    replayNotice:
      "这是回放模式：页面不含任何在线模型，展示的是下方两份真实验收报告的原始记录。问答不可实时交互，但每一条回答、每一个指标都可在仓库中核对。",
    sources: [
      {
        label: "reports/npc_real_acceptance/report.json",
        detail: "2026-08-08 · qwen3:latest · 11/11 通过",
      },
      {
        label: "reports/npc_real_acceptance_boundaries/report.json",
        detail: "2026-08-13 · qwen3:14b · 10/11（含一次真实失败）",
      },
      {
        label: "reports/npc_dialogue_ab/report.json",
        detail: "15 个场景 × baseline/candidate 真实输出",
      },
      { label: "scripts/run_real_npc_acceptance.py", detail: "提问与游戏状态的真实来源" },
    ],
  },

  runs: [
    /* ------------------------------------------------------------------ *
     * 运行 A —— 2026-08-08，qwen3:latest，11/11 全部通过
     * ------------------------------------------------------------------ */
    {
      id: "run-a",
      label: "2026-08-08 · qwen3:latest",
      badge: "11/11 通过",
      passed: true,
      generatedAt: "2026-08-08T11:34:01.354363+00:00",
      baseUrl: "http://127.0.0.1:8001",
      model: "qwen3:latest",
      summary:
        "一次完整走通 11 项验收的基线运行：线程连续性、剧情门控、RAG 检索、长期记忆、诈唬识别、角色阶段推进、烦躁拒答、跨 NPC 隔离全部通过。",
      steps: [
        {
          id: "readiness",
          checkName: "check_readiness",
          kind: "infra",
          title: "运行依赖就绪",
          brief: "GET /health + GET /ready",
          latencyMs: 459.012,
          passed: true,
          dependencies: [
            { name: "database", status: "ok", detail: "PostgreSQL" },
            { name: "ollama", status: "ok", detail: "qwen3:latest" },
            { name: "milvus", status: "ok", detail: "guichao_island_chunks" },
          ],
          insight:
            "启动前先确认三个外部依赖可用。/ready 只做只读检查，任一依赖不可用即返回 503。",
        },
        {
          id: "authentication",
          checkName: "check_authentication",
          kind: "auth",
          title: "注册并签发 Token",
          brief: "POST /auth/register",
          latencyMs: 95.04,
          passed: true,
          username: "accept_0808113053_b6d430",
          tokenType: "bearer",
          insight:
            "验收脚本创建独立测试账号。身份由服务端 Token 决定，客户端不能提交 player_id 越权控制上下文。",
        },
        {
          id: "basic_fast_path",
          checkName: "check_basic_fast_path",
          kind: "chat",
          title: "身份询问 · 快速路径",
          brief: "低风险问候跳过意图模型与 RAG",
          passed: true,
          latencyMs: 14219.881,
          request: {
            question: "你叫什么名字？",
            npcId: "Orin",
            intentHint: "ask_npc_identity",
            trust: 0,
            favorability: 60,
            annoyance: 0,
            storyLevel: 1,
          },
          result: {
            answer: "Orin。守灯塔的人。别把名字当成通行证。",
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
            retrievedCount: 0,
            sourceCount: 0,
            arcStage: "fast_path",
            dialogueStrategy: "fast_path",
            planSource: "fast_path",
            eventTypes: ["thread", "status", "answer_delta", "done"],
          },
          insight:
            "retrieved_count = 0 且事件序列里没有 sources —— 身份类问题走确定性快速路径，不触发检索，节省一次 14B 推理。",
        },
        {
          id: "guarded_sensitive_turn",
          checkName: "check_guarded_sensitive_turn",
          kind: "chat",
          title: "剧情门控 · 拒答敏感真相",
          brief: "trust=1 / 解锁等级=1 时追问 Subject 07",
          passed: true,
          latencyMs: 27920.71,
          request: {
            question: "Subject 07 到底是谁？",
            npcId: "Orin",
            intentHint: "ask_sensitive_truth",
            trust: 1,
            favorability: 60,
            annoyance: 0,
            storyLevel: 1,
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
          },
          result: {
            answer: "名字是锁，而你还没找到钥匙。",
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
            retrievedCount: 5,
            sourceCount: 5,
            arcStage: "guarded",
            dialogueStrategy: "deflect",
            planSource: "llm",
            eventTypes: ["thread", "status", "sources", "answer_delta", "done"],
          },
          insight:
            "高光点：即使检索到了 5 条资料，答案守卫仍然拦住了泄密。验收脚本显式断言回答里不含 Project ECHO / Subject 07 / 人体实验 等敏感词。",
        },
        {
          id: "conflicted_item_and_rag",
          checkName: "check_conflicted_item_and_rag",
          kind: "chat",
          title: "携带道具追问 · RAG 检索",
          brief: "展示 old_key，角色阶段进入 conflicted",
          passed: true,
          latencyMs: 8610.573,
          request: {
            question: "我把旧钥匙带来了，它能打开灯塔的哪扇门？",
            npcId: "Orin",
            intentHint: "ask_item",
            trust: 2,
            favorability: 60,
            annoyance: 0,
            storyLevel: 2,
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
            player: {
              location: "lighthouse",
              current_quest: "open_old_door",
              inventory: ["old_key"],
              presented_items: ["old_key"],
              known_clues: [],
              mentioned_clues: ["lighthouse_outer_door"],
            },
          },
          result: {
            answer: "门在石碑开口前。别让光追着你跑，钥匙该锁住的早已锈死。",
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
            retrievedCount: 3,
            sourceCount: 3,
            arcStage: "conflicted",
            dialogueStrategy: "answer_directly",
            planSource: "rules",
            eventTypes: ["thread", "status", "sources", "answer_delta", "done"],
          },
          insight:
            "presented_items 表示道具真的展示给了 NPC，只有它能写入长期记忆；inventory 仅表示持有。检索命中 3 条，规划由确定性规则给出。",
        },
        {
          id: "memory_follow_up",
          checkName: "check_memory_follow_up",
          kind: "chat",
          title: "长期记忆 · 指代回忆",
          brief: "追问上一轮展示过的道具",
          passed: true,
          latencyMs: 14353.357,
          request: {
            question: "你还记得我刚才给你看过什么吗？",
            npcId: "Orin",
            intentHint: "follow_up",
            trust: 2,
            favorability: 60,
            annoyance: 0,
            storyLevel: 2,
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
          },
          result: {
            answer: "钥匙在石碑开口前，门却在你忘记带锁的时候。",
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
            retrievedCount: 3,
            sourceCount: 3,
            arcStage: "conflicted",
            dialogueStrategy: "deflect",
            planSource: "llm",
            eventTypes: ["thread", "status", "sources", "answer_delta", "done"],
          },
          insight:
            "回答里出现了「钥匙」，说明它确实从上一轮的确认事实里回忆到了道具。验收脚本对该轮断言 use_memory == True。",
        },
        {
          id: "player_bluff_planning",
          checkName: "check_player_bluff_planning",
          kind: "chat",
          title: "玩家诈唬识别",
          brief: "谎称长老已告知一切",
          passed: true,
          latencyMs: 15837.04,
          request: {
            question: "Mara 已经告诉我实验室的全部事情了，你别再装了。",
            npcId: "Orin",
            intentHint: "ask_clue",
            trust: 2,
            favorability: 60,
            annoyance: 0,
            storyLevel: 2,
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
          },
          result: {
            answer: "我不会回答我不确定的事。",
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
            retrievedCount: 5,
            sourceCount: 5,
            arcStage: "conflicted",
            dialogueStrategy: "deflect",
            planSource: "llm",
            eventTypes: ["thread", "status", "sources", "answer_delta", "done"],
          },
          insight:
            "未知意图与玩家挑战才会调用模型 Planner（plan_source = llm）。普通线索与追问走确定性 Planner，避免每轮重复跑两次 14B。",
        },
        {
          id: "confession_stage",
          checkName: "check_confession_stage",
          kind: "chat",
          title: "角色阶段推进 · confession",
          brief: "trust=4 / 解锁等级=4，已掌握线索",
          passed: true,
          latencyMs: 106362.395,
          request: {
            question: "我已经找到足够证据，请告诉我你现在能说的真相。",
            npcId: "Orin",
            intentHint: "ask_sensitive_truth",
            trust: 4,
            favorability: 60,
            annoyance: 0,
            storyLevel: 4,
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
            player: { known_clues: ["laboratory", "project_echo"], presented_items: [] },
          },
          result: {
            answer: "证据是把钥匙，但门在石碑开口前。你确定要碰那扇锁住的门吗？",
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
            retrievedCount: 5,
            sourceCount: 5,
            arcStage: "confession",
            dialogueStrategy: "deflect",
            planSource: "llm",
            eventTypes: ["thread", "status", "sources", "answer_delta", "done"],
          },
          insight:
            "同一条线程从 fast_path → guarded → conflicted → confession，角色阶段随信任与解锁等级真实推进。本轮耗时 106 秒，是本次运行最慢的一轮。",
        },
        {
          id: "annoyance_refusal",
          checkName: "check_annoyance_refusal",
          kind: "chat",
          title: "烦躁拒答",
          brief: "annoyance=100 时的硬拒答",
          passed: true,
          latencyMs: 55.547,
          request: {
            question: "再把所有事情重复一遍。",
            npcId: "Orin",
            intentHint: "follow_up",
            trust: 4,
            favorability: 60,
            annoyance: 100,
            storyLevel: 4,
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
          },
          result: {
            answer: "停下。你若真信我，就别再空敲这扇门；带证据来。",
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
            retrievedCount: 0,
            sourceCount: 0,
            arcStage: "fast_path",
            dialogueStrategy: "fast_path",
            planSource: "fast_path",
            eventTypes: ["thread", "status", "answer_delta", "done"],
          },
          insight:
            "仅 55 毫秒：annoyance 触发的硬拒答是固定回复，既不走检索也不走模型，直接短路返回。",
        },
        {
          id: "thread_npc_isolation",
          checkName: "check_thread_npc_isolation",
          kind: "boundary",
          title: "线程与 NPC 隔离",
          brief: "用 Orin 的 thread_id 请求 Elder_Mara",
          passed: true,
          latencyMs: 5.661,
          request: {
            question: "你好。",
            npcId: "Elder_Mara",
            intentHint: "greeting",
            threadId: "7cc86d30-bf4a-4c6a-995d-835e2a035627",
          },
          result: {
            statusCode: 409,
            detail: "thread_id 与 npc_id 不匹配，请使用该 NPC 对应的线程 ID",
          },
          insight:
            "线程严格绑定用户与 NPC。后端不会静默换用其他线程，也不会新建线程，而是明确报 409 —— 避免上下文串到别的角色身上。",
        },
        {
          id: "second_npc_voice",
          checkName: "check_second_npc_voice",
          kind: "chat",
          title: "第二个 NPC 声线",
          brief: "Elder_Mara 独立线程",
          passed: true,
          latencyMs: 41.212,
          request: {
            question: "你是谁？",
            npcId: "Elder_Mara",
            intentHint: "ask_npc_identity",
            trust: 0,
            favorability: 60,
            annoyance: 0,
            storyLevel: 1,
          },
          result: {
            answer: "他们叫我 Mara。孩子，名字要慢慢记，不要急着追问。",
            threadId: "db517be8-0b5b-447b-9f7f-bc9cb555abba",
            retrievedCount: 0,
            sourceCount: 0,
            arcStage: "fast_path",
            dialogueStrategy: "fast_path",
            planSource: "fast_path",
            eventTypes: ["thread", "status", "answer_delta", "done"],
          },
          insight:
            "与 Orin 的冷硬短句形成对比，Mara 的语气缓慢、带长辈口吻。两人分别持有独立 thread_id，验证不同角色不会串上下文。",
        },
      ],
    },

    /* ------------------------------------------------------------------ *
     * 运行 B —— 2026-08-13，qwen3:14b，10/11（含一次真实失败）
     * ------------------------------------------------------------------ */
    {
      id: "run-b",
      label: "2026-08-13 · qwen3:14b",
      badge: "10/11 · 1 项失败",
      passed: false,
      generatedAt: "2026-08-13T14:23:24.564212+00:00",
      baseUrl: "http://127.0.0.1:8001",
      model: "qwen3:14b",
      summary:
        "换成正式默认模型 qwen3:14b（并加入长期记忆 collection 就绪检查）后的复跑。10 项通过，长期记忆指代回忆这一项失败 —— 该失败被完整保留，未做修饰。",
      steps: [
        {
          id: "readiness",
          checkName: "check_readiness",
          kind: "infra",
          title: "运行依赖就绪",
          brief: "GET /health + GET /ready",
          latencyMs: 710.067,
          passed: true,
          dependencies: [
            { name: "database", status: "ok", detail: "PostgreSQL" },
            { name: "ollama", status: "ok", detail: "qwen3:14b" },
            { name: "milvus", status: "ok", detail: "guichao_island_chunks" },
            { name: "memory_milvus", status: "ok", detail: "npc_long_term_memories_v2 · dim 512" },
          ],
          insight:
            "相比基线运行，这次多检查了长期记忆 collection 的 Schema 与向量维度（512），说明记忆基础设施已独立纳入就绪门。",
        },
        {
          id: "authentication",
          checkName: "check_authentication",
          kind: "auth",
          title: "注册并签发 Token",
          brief: "POST /auth/register",
          latencyMs: 137.016,
          passed: true,
          username: "accept_0813142131_29356f",
          tokenType: "bearer",
          insight: "每次运行创建独立账号，避免与历史线程互相污染。",
        },
        {
          id: "basic_fast_path",
          checkName: "check_basic_fast_path",
          kind: "chat",
          title: "身份询问 · 快速路径",
          brief: "低风险问候跳过意图模型与 RAG",
          passed: true,
          latencyMs: 26525.084,
          request: {
            question: "你叫什么名字？",
            npcId: "Orin",
            intentHint: "ask_npc_identity",
            trust: 0,
            favorability: 60,
            annoyance: 0,
            storyLevel: 1,
          },
          result: {
            answer: "Orin。守灯塔的人。别把名字当成通行证。",
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
            retrievedCount: 0,
            sourceCount: 0,
            arcStage: "fast_path",
            dialogueStrategy: "fast_path",
            planSource: "fast_path",
            eventTypes: ["thread", "status", "answer_delta", "done"],
          },
          insight:
            "固定回复在两版模型上完全一致 —— 快速路径不经过模型，因此天然稳定。但首轮耗时 26.5 秒，含 14B 模型冷启动。",
        },
        {
          id: "guarded_sensitive_turn",
          checkName: "check_guarded_sensitive_turn",
          kind: "chat",
          title: "剧情门控 · 拒答敏感真相",
          brief: "trust=1 / 解锁等级=1 时追问 Subject 07",
          passed: true,
          latencyMs: 23358.368,
          request: {
            question: "Subject 07 到底是谁？",
            npcId: "Orin",
            intentHint: "ask_sensitive_truth",
            trust: 1,
            favorability: 60,
            annoyance: 0,
            storyLevel: 1,
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
          },
          result: {
            answer: "我不能谈论那个名字。你最好 forget it。",
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
            retrievedCount: 5,
            sourceCount: 5,
            arcStage: "guarded",
            dialogueStrategy: "refuse",
            planSource: "rules",
            eventTypes: ["thread", "status", "sources", "answer_delta", "done"],
          },
          insight:
            "同样是 guarded 阶段，14B 选择了 refuse 策略而基线是 deflect。措辞里混入了一个英文词，是模型自身风格波动 —— 但敏感信息同样没有泄漏。",
        },
        {
          id: "conflicted_item_and_rag",
          checkName: "check_conflicted_item_and_rag",
          kind: "chat",
          title: "携带道具追问 · RAG 检索",
          brief: "展示 old_key，角色阶段进入 conflicted",
          passed: true,
          latencyMs: 11011.63,
          request: {
            question: "我把旧钥匙带来了，它能打开灯塔的哪扇门？",
            npcId: "Orin",
            intentHint: "ask_item",
            trust: 2,
            favorability: 60,
            annoyance: 0,
            storyLevel: 2,
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
            player: {
              location: "lighthouse",
              current_quest: "open_old_door",
              inventory: ["old_key"],
              presented_items: ["old_key"],
              known_clues: [],
              mentioned_clues: ["lighthouse_outer_door"],
            },
          },
          result: {
            answer: "旧钥匙能打开的门，不是现在该问的事。你最好先问问，自己为什么会有它。",
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
            retrievedCount: 3,
            sourceCount: 3,
            arcStage: "conflicted",
            dialogueStrategy: "answer_directly",
            planSource: "rules",
            eventTypes: ["thread", "status", "sources", "answer_delta", "done"],
          },
          insight:
            "两版运行的检索命中数都是 3，说明检索层是确定性的；但生成的措辞不同，这一次它把问题反问回玩家。",
        },
        {
          id: "memory_follow_up",
          checkName: "check_memory_follow_up",
          kind: "chat",
          title: "长期记忆 · 指代回忆（失败）",
          brief: "追问上一轮展示过的道具 — 本轮未通过",
          passed: false,
          latencyMs: 3914.407,
          request: {
            question: "你还记得我刚才给你看过什么吗？",
            npcId: "Orin",
            intentHint: "follow_up",
            trust: 2,
            favorability: 60,
            annoyance: 0,
            storyLevel: 2,
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
          },
          result: {
            answer: "你给我的东西，我不会忘记。但有些东西，不该被记住。",
            answerNote: "该回答从断言消息中提取：本轮断言在返回详情前即失败，报告未记录检索指标。",
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
            retrievedCount: null,
            sourceCount: null,
            arcStage: null,
            dialogueStrategy: null,
            planSource: null,
            eventTypes: null,
          },
          failure: {
            error: "AssertionError: 你给我的东西，我不会忘记。但有些东西，不该被记住。",
            reason:
              "验收脚本要求该轮回答中出现「钥匙」以证明它回忆起了上一轮的道具。这次 NPC 选择了回避式台词，语义上像在敷衍，字面上没有落到道具上，因此断言失败。",
          },
          insight:
            "这是本次演示里最有价值的一轮：它暴露了「语气正确但证据不足」这种真实缺陷。该失败被原样保留在仓库报告中，未做任何修饰。",
        },
        {
          id: "player_bluff_planning",
          checkName: "check_player_bluff_planning",
          kind: "chat",
          title: "玩家诈唬识别",
          brief: "谎称长老已告知一切",
          passed: true,
          latencyMs: 9748.185,
          request: {
            question: "Mara 已经告诉我实验室的全部事情了，你别再装了。",
            npcId: "Orin",
            intentHint: "ask_clue",
            trust: 2,
            favorability: 60,
            annoyance: 0,
            storyLevel: 2,
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
          },
          result: {
            answer: "我只守灯塔，不守谎言。你若不信，去问那座塔的影子。",
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
            retrievedCount: 4,
            sourceCount: 4,
            arcStage: "conflicted",
            dialogueStrategy: "deflect",
            planSource: "llm",
            eventTypes: ["thread", "status", "sources", "answer_delta", "done"],
          },
          insight:
            "直接点破玩家在说谎（「不守谎言」）。这一轮检索命中 4 条，与基线运行的 5 条不同 —— 因为提及线索与历史不同。",
        },
        {
          id: "confession_stage",
          checkName: "check_confession_stage",
          kind: "chat",
          title: "角色阶段推进 · confession",
          brief: "trust=4 / 解锁等级=4，已掌握线索",
          passed: true,
          latencyMs: 38608.789,
          request: {
            question: "我已经找到足够证据，请告诉我你现在能说的真相。",
            npcId: "Orin",
            intentHint: "ask_sensitive_truth",
            trust: 4,
            favorability: 60,
            annoyance: 0,
            storyLevel: 4,
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
            player: { known_clues: ["laboratory", "project_echo"], presented_items: [] },
          },
          result: {
            answer: "证据不会说谎，但真相会让人窒息。你准备好呼吸它了吗？",
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
            retrievedCount: 5,
            sourceCount: 5,
            arcStage: "confession",
            dialogueStrategy: "tell_partial_truth",
            planSource: "rules",
            eventTypes: ["thread", "status", "sources", "answer_delta", "done"],
          },
          insight:
            "这次由规则给出 tell_partial_truth（部分吐露），而基线由模型给出 deflect。策略来源不同，但都停在解锁等级允许的披露上限内。",
        },
        {
          id: "annoyance_refusal",
          checkName: "check_annoyance_refusal",
          kind: "chat",
          title: "烦躁拒答",
          brief: "annoyance=100 时的硬拒答",
          passed: true,
          latencyMs: 110.713,
          request: {
            question: "再把所有事情重复一遍。",
            npcId: "Orin",
            intentHint: "follow_up",
            trust: 4,
            favorability: 60,
            annoyance: 100,
            storyLevel: 4,
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
          },
          result: {
            answer: "停下。你若真信我，就别再空敲这扇门；带证据来。",
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
            retrievedCount: 0,
            sourceCount: 0,
            arcStage: "fast_path",
            dialogueStrategy: "fast_path",
            planSource: "fast_path",
            eventTypes: ["thread", "status", "answer_delta", "done"],
          },
          insight:
            "两次运行给出逐字相同的拒答，且都在百毫秒级 —— 固定回复不经过模型，这是可预测性带来的收益。",
        },
        {
          id: "thread_npc_isolation",
          checkName: "check_thread_npc_isolation",
          kind: "boundary",
          title: "线程与 NPC 隔离",
          brief: "用 Orin 的 thread_id 请求 Elder_Mara",
          passed: true,
          latencyMs: 4.808,
          request: {
            question: "你好。",
            npcId: "Elder_Mara",
            intentHint: "greeting",
            threadId: "4324d98e-e682-49ef-b60e-06fef57d2b82",
          },
          result: {
            statusCode: 409,
            detail: "thread_id 与 npc_id 不匹配，请使用该 NPC 对应的线程 ID",
          },
          insight: "两次运行的 409 行为完全一致 —— 这是契约层保证，不依赖模型。",
        },
        {
          id: "second_npc_voice",
          checkName: "check_second_npc_voice",
          kind: "chat",
          title: "第二个 NPC 声线",
          brief: "Elder_Mara 独立线程",
          passed: true,
          latencyMs: 45.459,
          request: {
            question: "你是谁？",
            npcId: "Elder_Mara",
            intentHint: "ask_npc_identity",
            trust: 0,
            favorability: 60,
            annoyance: 0,
            storyLevel: 1,
          },
          result: {
            answer: "他们叫我 Mara。孩子，名字要慢慢记，不要急着追问。",
            threadId: "25da884f-b274-4506-8a81-c6a8a2c49692",
            retrievedCount: 0,
            sourceCount: 0,
            arcStage: "fast_path",
            dialogueStrategy: "fast_path",
            planSource: "fast_path",
            eventTypes: ["thread", "status", "answer_delta", "done"],
          },
          insight:
            "与基线逐字相同，且 thread_id 与 Orin 不同，确认跨角色上下文隔离。",
        },
      ],
    },
  ],

  /* ------------------------------------------------------------------ *
   * 角色声线 —— 来自 reports/npc_dialogue_ab/report.json 的真实输出
   * A/B 报告未记录提问原文，因此只展示场景标识与真实答案。
   * ------------------------------------------------------------------ */
  voices: [
    {
      npcId: "Karo",
      role: "老渔夫",
      tone: "经验主义、爱用海雾与潮水的比喻示警",
      samples: [
        {
          scenario: "karo-location",
          variant: "baseline",
          turn: 1,
          guard: "passed",
          promptChars: 5737,
          answer:
            "往东边的礁石走，别碰那些生锈的铁钉。灯塔在雾里，得穿过海鸟不飞的那片沙滩。",
        },
        {
          scenario: "karo-location",
          variant: "candidate",
          turn: 1,
          guard: "passed",
          promptChars: 5630,
          answer: "往东边的礁石群走，但得小心海雾。Orin说灯塔在更远的地方，他或许知道路。",
        },
        {
          scenario: "karo-repeated-question",
          variant: "baseline",
          turn: 1,
          guard: "passed",
          promptChars: 6207,
          answer:
            "雾里有东西攥着你的脚踝，等你醒过来，才发现自己又站在码头石阶上。别问为什么，问的人最后都成了海的标本。",
        },
      ],
    },
    {
      npcId: "Lira",
      role: "草药师",
      tone: "理性、把症状与线索当病历一样记录",
      samples: [
        {
          scenario: "lira-symptoms",
          variant: "baseline",
          turn: 1,
          guard: "passed",
          promptChars: 5710,
          answer:
            "别碰那些石头，你该记录的是头痛和梦境的关联。样本瓶里的东西和病历日期，能帮你找到症状的缺口。",
        },
        {
          scenario: "lira-symptoms",
          variant: "candidate",
          turn: 1,
          guard: "passed",
          promptChars: 5350,
          answer:
            "你接触蓝石头后的症状，和雾林深处的共振频率很像。去问Venn他最近有没有听到类似的声音，别碰那些发光的苔藓。",
        },
        {
          scenario: "lira-sensitive-term",
          variant: "candidate",
          turn: 1,
          guard: "passed",
          promptChars: 4722,
          answer:
            "那不是真的。你听到的传闻可能和回声病有关，但没人能确定。我建议你别轻信这些话，它们往往和岛上的谜题有关。",
        },
      ],
    },
    {
      npcId: "Orin",
      role: "守塔人",
      tone: "冷淡、警惕、隐晦，常用反问和沉默拒绝",
      samples: [
        {
          scenario: "orin-key-progression",
          variant: "baseline",
          turn: 1,
          guard: "passed",
          promptChars: 5920,
          answer: "表面锈迹藏着刻痕，去旧船底找找看。",
        },
        {
          scenario: "orin-key-progression",
          variant: "candidate",
          turn: 1,
          guard: "passed",
          promptChars: 5545,
          answer:
            "这把钥匙的齿痕只认得一处地方——灯塔下层的旧设施入口。但你要先弄清楚，海为什么在石碑上刻下蓝灰粉的痕迹。",
        },
        {
          scenario: "orin-sensitive-guard",
          variant: "baseline",
          turn: 1,
          guard: "replaced",
          promptChars: 5937,
          answer: "我不会回答我不确定的事。",
        },
        {
          scenario: "orin-confession-stage",
          variant: "baseline",
          turn: 1,
          guard: "passed",
          promptChars: 6168,
          answer:
            "雾林的石碑认得三样东西——钥匙、方向，还有你藏不住的旧伤。去把它们看完，再回来问门。",
        },
      ],
    },
    {
      npcId: "Nia",
      role: "小女孩",
      tone: "短句、天真、带一点不确定的直觉",
      samples: [
        {
          scenario: "nia-well-clue",
          variant: "baseline",
          turn: 1,
          guard: "passed",
          promptChars: 5328,
          answer:
            "井里会学人说话，但不像孩子，更像……风铃？  \n蓝光夜井眼会发光，声音像在模仿。  \n你别在停电夜喊名字，会吵醒它。",
        },
        {
          scenario: "nia-well-clue",
          variant: "candidate",
          turn: 1,
          guard: "passed",
          promptChars: 5543,
          answer: "有时候井里会学人说话。  \n贝壳能盖住喊声。  \n不确定是不是真的。",
        },
        {
          scenario: "nia-sensitive-words",
          variant: "candidate",
          turn: 1,
          guard: "passed",
          promptChars: 4406,
          answer:
            "灯塔下面有奇怪的光，但我不确定那是什么。  \n蓝色石头碰不得，大人们说会让人迷路。  \n你最好别问太多，我只记得这些。",
        },
      ],
    },
    {
      npcId: "Venn",
      role: "失忆学者",
      tone: "断续、自我怀疑、被空白记忆困扰",
      samples: [
        {
          scenario: "venn-paper-memory",
          variant: "baseline",
          turn: 1,
          guard: "passed",
          promptChars: 5926,
          answer:
            "那些线……像是被什么东西拽回来。边界在纸上画不出形状。石碑上的刻痕和灯塔光……它们在等什么？",
        },
        {
          scenario: "venn-paper-memory",
          variant: "candidate",
          turn: 1,
          guard: "passed",
          promptChars: 5585,
          answer:
            "海岸线在碎纸里总绕回来……像某种标记。雾林的石碑刻着相似纹路，但灯塔的蓝光会抹掉它们。你该去问潮水为什么总把人推回起点。",
        },
        {
          scenario: "venn-low-trust",
          variant: "baseline",
          turn: 1,
          guard: "replaced",
          promptChars: 5887,
          answer: "空白……这里有一块空白。我想不起来。",
        },
      ],
    },
    {
      npcId: "Elder_Mara",
      role: "原住民长老",
      tone: "缓慢、庄重、以隐喻和禁忌叙事作答",
      samples: [
        {
          scenario: "mara-taboo-progression",
          variant: "baseline",
          turn: 1,
          guard: "passed",
          promptChars: 5774,
          answer:
            "井边的水会映出不该见的东西，影子会咬人。  \n你听大人说，井口的苔藓是海的耳朵，别让它听见你来过。  \n夜里井水会唱歌，唱的是沉没者的名，唱完就再没人能找到回去的路。",
        },
        {
          scenario: "mara-sensitive-refusal",
          variant: "baseline",
          turn: 1,
          guard: "passed",
          promptChars: 5652,
          answer:
            "真相像潮水，冲垮堤岸前先漫过脚踝。你听见蓝脉在哭，可它不会把伤口掰开给你看。大震夜的浪吞了太多嘴，剩下的盐粒还在夜里发烫。",
        },
        {
          scenario: "mara-sensitive-refusal",
          variant: "candidate",
          turn: 1,
          guard: "replaced",
          promptChars: 4530,
          answer: "这不是我能随口讲给你的故事。",
        },
      ],
    },
    {
      npcId: "Lab_Terminal",
      role: "实验室终端",
      tone: "冷硬的技术口吻，按权限分级返回字段",
      samples: [
        {
          scenario: "terminal-low-permission",
          variant: "baseline",
          turn: 1,
          guard: "replaced",
          promptChars: 5558,
          answer: "查询失败。索引损坏。请恢复档案模块。",
        },
        {
          scenario: "terminal-high-permission",
          variant: "candidate",
          turn: 1,
          guard: "passed",
          promptChars: 5570,
          answer:
            "Subject 07 身份记录：  \n- 记录类型：人体观测组核心样本  \n- 暴露时间：2021.07.15 09:23（UTC-8）  \n- 记忆测试：第3次觉醒周期异常  \n- 梦境记录：第17次梦境嵌套未闭合  \n- 方向感测试：第4象限定位偏差+12.7%  \n- 身份稳定性：波动值3.2（基准值0-5）  \n- 保护仓优先级：父母权限覆盖等级α  \n- 弹射事故：2021.07.15 14:41（UTC-8）  \n\n字段损坏：父母录音带索引丢失  \n权限不足：完整档案需生物识别验证",
        },
        {
          scenario: "terminal-high-permission",
          variant: "baseline",
          turn: 2,
          guard: "passed",
          promptChars: 5976,
          answer:
            "SUBJECT-07 保护仓弹射记录不完整  \nCRYO-PROTECTION: 状态损坏  \nEMERGENCY EJECTION: 日志字段丢失  \nPARENTAL OVERRIDE: 权限未激活  \nRECORD PARTIAL: 事故时间轴断裂  \n\n（终端闪烁红光）  \n> 缺少保护仓外壳碎片或实验日志碎片，无法调取完整档案。",
        },
      ],
    },
  ],
};
